FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm install
RUN npm run build --workspace=inkrockit-web

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=base /app/apps/web/.next/standalone ./standalone
COPY --from=base /app/apps/web/.next/static ./standalone/apps/web/.next/static
COPY --from=base /app/apps/web/public ./standalone/apps/web/public
EXPOSE 3000
CMD ["node", "standalone/apps/web/server.js"]
